zone = "cn-hangzhou-c"
instance_type = "ecs.t5-lc1m1.small"
instance_name = "cloudiac-example-qa"
vpc_name = "vpc-cloudiac-example-qa"
sg_name = "sg-cloudiac-example-qa"
cidr_block = "192.168.0.0/24"
